name: '持续集成'

on:
  push:
    branches: # branches: ["master","dev"] 指定多个分支
      - master
    # paths: # 指定目录有变化时触发 actions
    #   - src/*

jobs:
  build: # job id
    runs-on: ubuntu-latest # 指定 actions 执行系统，有 8 种可以选择
    steps: # job 执行步骤
      # 使用现成的 actions
      - uses: actions/checkout@v1 # github 的 actions  拉取代码
      - name: first step # 给这个步骤取一个名字
        # 不取名字 - run echo Hello,World!
        run: echo Hello,world!
      - name: 测试一个脚本
        run: |
          echo Add other actions to build.
          echo test, and deploy your project.
      - uses: actions/setup-node@v3 # 设置node环境 TODO @v3 表示什么？
      - run: |
          git config --global user.email "jackchou4job@163.com"
          git config --global user.name "JackChou"
      - run: |
          npm i
          npm run deploy
