name: '持续集成'

on: 
 push:
  branches:
   - master

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v1
   - name: Run a one-line script
     run: echo Hello,world!
   - name: 测试一个脚本
     run: |
        echo Add other actions to build.
        echo test, and deploy your project.
